spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

jwt:
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 8640000
  secret-key: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==